PreDevResourceGroupName               = "tesco-data-sharing-rg"
PreDevKeyVaultName                     = "PreDevKV"
StorageAccountContainerName                  = "terrastates01"
location                                = "West Europe"
PreDevStorageAccountName = "predevstorage"
## v_CoreSubscriptionId = "${ARM_SUBSCRIPTION_ID}"