PreDevResourceGroupName               = "tesco-data-sharing-rg"
PreDevKeyVaultName                     = "PreDevKV"
StorageAccountContainerName                  = "terrastates01"
location                                = "UK South"
PreDevStorageAccountName = "predevstorage"
v_CoreSubscriptionId = "e03c12ba-7039-4182-877b-3e38a905e42c"